from pygame import Color, Vector2
# BOOLEANS
SHOW_FPS: bool = True

# NUMERICS
SCREEN_SIZE: Vector2 = Vector2(1600, 900)
DEFAULT_TILE_SIZE: int = 32
DEFAULT_SHAPE_SIZE: Vector2 = Vector2(DEFAULT_TILE_SIZE, DEFAULT_TILE_SIZE)
FRAME_RATE: int = 30

# COLORS
BACKGROUND_COLOR: Color = Color(205, 205, 205)
